// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Block_Mat_exit3_proc (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        src_rows,
        src_cols,
        dst_rows,
        src_mat_rows_out_din,
        src_mat_rows_out_full_n,
        src_mat_rows_out_write,
        src_mat_cols_out_din,
        src_mat_cols_out_full_n,
        src_mat_cols_out_write,
        select_ln60_out_out_din,
        select_ln60_out_out_full_n,
        select_ln60_out_out_write,
        src_rows_cast1_out_out_din,
        src_rows_cast1_out_out_full_n,
        src_rows_cast1_out_out_write,
        src_cols_cast2_out_out_din,
        src_cols_cast2_out_out_full_n,
        src_cols_cast2_out_out_write
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] src_rows;
input  [31:0] src_cols;
input  [31:0] dst_rows;
output  [31:0] src_mat_rows_out_din;
input   src_mat_rows_out_full_n;
output   src_mat_rows_out_write;
output  [31:0] src_mat_cols_out_din;
input   src_mat_cols_out_full_n;
output   src_mat_cols_out_write;
output  [2:0] select_ln60_out_out_din;
input   select_ln60_out_out_full_n;
output   select_ln60_out_out_write;
output  [11:0] src_rows_cast1_out_out_din;
input   src_rows_cast1_out_out_full_n;
output   src_rows_cast1_out_out_write;
output  [11:0] src_cols_cast2_out_out_din;
input   src_cols_cast2_out_out_full_n;
output   src_cols_cast2_out_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg src_mat_rows_out_write;
reg src_mat_cols_out_write;
reg select_ln60_out_out_write;
reg src_rows_cast1_out_out_write;
reg src_cols_cast2_out_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    src_mat_rows_out_blk_n;
reg    src_mat_cols_out_blk_n;
reg    select_ln60_out_out_blk_n;
reg    src_rows_cast1_out_out_blk_n;
reg    src_cols_cast2_out_out_blk_n;
reg    ap_block_state1;
wire   [0:0] icmp_ln60_fu_105_p2;
wire   [0:0] icmp_ln57_fu_99_p2;
wire   [0:0] or_ln60_fu_111_p2;
wire   [2:0] select_ln60_fu_117_p3;
reg   [0:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln60_out_out_blk_n = select_ln60_out_out_full_n;
    end else begin
        select_ln60_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        select_ln60_out_out_write = 1'b1;
    end else begin
        select_ln60_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_out_out_blk_n = src_cols_cast2_out_out_full_n;
    end else begin
        src_cols_cast2_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_cols_cast2_out_out_write = 1'b1;
    end else begin
        src_cols_cast2_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_cols_out_blk_n = src_mat_cols_out_full_n;
    end else begin
        src_mat_cols_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_cols_out_write = 1'b1;
    end else begin
        src_mat_cols_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_rows_out_blk_n = src_mat_rows_out_full_n;
    end else begin
        src_mat_rows_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_mat_rows_out_write = 1'b1;
    end else begin
        src_mat_rows_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_out_out_blk_n = src_rows_cast1_out_out_full_n;
    end else begin
        src_rows_cast1_out_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        src_rows_cast1_out_out_write = 1'b1;
    end else begin
        src_rows_cast1_out_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (src_cols_cast2_out_out_full_n == 1'b0) | (src_rows_cast1_out_out_full_n == 1'b0) | (select_ln60_out_out_full_n == 1'b0) | (src_mat_cols_out_full_n == 1'b0) | (src_mat_rows_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign icmp_ln57_fu_99_p2 = ((dst_rows == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_105_p2 = ((dst_rows == 32'd2) ? 1'b1 : 1'b0);

assign or_ln60_fu_111_p2 = (icmp_ln60_fu_105_p2 | icmp_ln57_fu_99_p2);

assign select_ln60_fu_117_p3 = ((icmp_ln60_fu_105_p2[0:0] === 1'b1) ? 3'd6 : 3'd5);

assign select_ln60_out_out_din = ((or_ln60_fu_111_p2[0:0] === 1'b1) ? select_ln60_fu_117_p3 : 3'd4);

assign src_cols_cast2_out_out_din = src_cols[11:0];

assign src_mat_cols_out_din = src_cols;

assign src_mat_rows_out_din = src_rows;

assign src_rows_cast1_out_out_din = src_rows[11:0];

assign start_out = real_start;

endmodule //Block_Mat_exit3_proc
